replicaCount: 2

image:
  repository: ghcr.io/kabirou-code/kabirou-oumarou
  tag: "e0e80663407a53896e499f15c812f2414e0add0a"
  pullPolicy: Always

nameOverride: "kabirou-oumarou"
fullnameOverride: "kabirou-oumarou"

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

ingress:
  enabled: false
